### ISSUE TITLE
about the project code wrong

### ISSUE THREAD

**Issue by Afleve** [Visual-AI/SPTNet#1] opened 2024-03-08 13:27 UTC
Thank for your code.
But I found there're some wrong.
`from project_utils.general_utils
from methods.vpt.utils import cosine_lr`
I found general_utils in util,but couldn't cosine_lr

**Comment by whj363636** [comment] 2024-03-08 13:53
Hi @Onenormler,

Thanks for your interest. The inconsistency you point out caused by refactoring has been fixed now.

**Comment by qingsonghu08** [comment] 2024-03-11 08:34
NameError: name 'unfreeze' is not defined
`from util.general_utils import freeze, unfreeze`
But I found there is no freeze and unfreeze in general_utils

**Closed as completed** 2024-03-11 08:37 UTC

**Comment by whj363636** [comment] 2024-03-11 08:38
Hi @qingsonghu08,

Thanks for pointing that out. Already updated it!
